"""V2 text/tag retrieval package."""

from .documents import build_archive_documents, build_feature_vocabulary, load_archive_documents, write_archive_documents
from .encoder import SigLIP2TextEncoder, SigLIP2TextEncoderConfig
from .index import build_archive_index
from .llm_parser import LUXIA_CHAT_URL, LuxiaQueryParser, LuxiaQueryParserConfig
from .models import (
    ATTRIBUTE_NAMES,
    MULTI_VALUE_ATTRIBUTES,
    MULTI_VALUE_SEPARATOR,
    LocalIndexStore,
    QueryParser,
    Stage,
    TextEncoder,
    V2ArchiveDocument,
    V2ArchiveIndex,
    V2IndexedDocument,
    V2ParsedQuery,
    V2PipelineInput,
    V2PipelineOutput,
    V2RankedResult,
)
from .preprocessing import (
    CompletedBatchResult,
    DEFAULT_LOCAL_VLM_MODEL,
    DEFAULT_OPENAI_VISION_MODEL,
    DEFAULT_OUTPUT_ROOT,
    FullTagStageResult,
    InventoryStageResult,
    NormalizeStageResult,
    RecoveredFullTagResult,
    SampleStageResult,
    SubmittedBatchResult,
    TaggingStageSummary,
    V2PreprocessingPaths,
    build_preprocessing_paths,
    collect_full_tag_batch,
    recover_full_tag_from_logs,
    read_normalized_tag_rows,
    read_raw_tag_rows,
    run_full_tag_stage,
    run_inventory_stage,
    run_normalize_stage,
    run_sample_first_stage,
    submit_full_tag_batch,
    summarize_raw_tags,
)
from .pipeline import V2Pipeline, V2PipelineConfig, dense_cosine_similarity
from .storage import InMemoryArchiveIndex, JsonArchiveIndexStore
from .tag_ranker import FeatureMatchResult, TagRanker, TagRankerConfig, classify_feature_match

__all__ = [
    "ATTRIBUTE_NAMES",
    "DEFAULT_LOCAL_VLM_MODEL",
    "DEFAULT_OPENAI_VISION_MODEL",
    "DEFAULT_OUTPUT_ROOT",
    "CompletedBatchResult",
    "FullTagStageResult",
    "FeatureMatchResult",
    "InMemoryArchiveIndex",
    "InventoryStageResult",
    "JsonArchiveIndexStore",
    "LocalIndexStore",
    "LUXIA_CHAT_URL",
    "LuxiaQueryParser",
    "LuxiaQueryParserConfig",
    "MULTI_VALUE_ATTRIBUTES",
    "MULTI_VALUE_SEPARATOR",
    "NormalizeStageResult",
    "QueryParser",
    "RecoveredFullTagResult",
    "SampleStageResult",
    "SigLIP2TextEncoder",
    "SigLIP2TextEncoderConfig",
    "Stage",
    "SubmittedBatchResult",
    "TaggingStageSummary",
    "TagRanker",
    "TagRankerConfig",
    "TextEncoder",
    "V2ArchiveDocument",
    "V2ArchiveIndex",
    "V2IndexedDocument",
    "V2ParsedQuery",
    "V2Pipeline",
    "V2PipelineConfig",
    "V2PipelineInput",
    "V2PipelineOutput",
    "V2PreprocessingPaths",
    "V2RankedResult",
    "build_archive_documents",
    "build_archive_index",
    "build_feature_vocabulary",
    "build_preprocessing_paths",
    "collect_full_tag_batch",
    "classify_feature_match",
    "dense_cosine_similarity",
    "load_archive_documents",
    "recover_full_tag_from_logs",
    "read_normalized_tag_rows",
    "read_raw_tag_rows",
    "run_full_tag_stage",
    "run_inventory_stage",
    "run_normalize_stage",
    "run_sample_first_stage",
    "submit_full_tag_batch",
    "summarize_raw_tags",
    "write_archive_documents",
]
