"""Tagging, preprocessing, and synonym utilities for Switch Query."""

from .attributes import DEFAULT_ATTRIBUTE_NAMES
from .local_vlm_tagger import DEFAULT_MODEL, DEFAULT_PROMPT, run_local_vlm
from .preprocessing import (
    BlankTagger,
    CanonicalMappingRow,
    FrequencyRow,
    InventoryRow,
    NormalizedTagRow,
    RawTagRow,
    RetrievalEvalRow,
    RetrievalQuery,
    SampleRow,
    SubprocessJsonTagger,
    TaggingResult,
    apply_canonical_mappings,
    build_default_queries,
    build_frequency_rows,
    build_full_manifest,
    build_image_inventory,
    build_sample_manifest,
    evaluate_retrieval,
    read_canonical_mappings,
    run_rough_tagging,
    seed_canonical_mappings,
    write_csv,
)
from .synonyms import SynonymCatalog

__all__ = [
    "BlankTagger",
    "CanonicalMappingRow",
    "DEFAULT_ATTRIBUTE_NAMES",
    "DEFAULT_MODEL",
    "DEFAULT_PROMPT",
    "FrequencyRow",
    "InventoryRow",
    "NormalizedTagRow",
    "RawTagRow",
    "RetrievalEvalRow",
    "RetrievalQuery",
    "SampleRow",
    "SubprocessJsonTagger",
    "SynonymCatalog",
    "TaggingResult",
    "apply_canonical_mappings",
    "build_default_queries",
    "build_frequency_rows",
    "build_full_manifest",
    "build_image_inventory",
    "build_sample_manifest",
    "evaluate_retrieval",
    "read_canonical_mappings",
    "run_local_vlm",
    "run_rough_tagging",
    "seed_canonical_mappings",
    "write_csv",
]
